#+TITLE: Yesterday, You Said Tomorrow
#+DESCRIPTION: Sharing Work in Progress
#+TAGS: Discussion
#+TAGS: Daily Dispatch
#+TAGS: Meta
#+DATE: 2020-08-18
#+SLUG: yesterday-you-said-tomorrow
#+LINK: shia-labeouf-just-do-it https://www.youtube.com/watch?v=iAg4yMangmY
#+LINK: cal-newport-deep-work https://www.calnewport.com/books/deep-work/
#+LINK: austin-kleon-steal-like-an-artist https://austinkleon.com/steal/
#+LINK: austin-kleon-show-your-work https://austinkleon.com/show-your-work/
#+LINK: notebookskills https://www.dur.ac.uk/resources/physics/students/labs/skills/notebookskills.pdf
#+LINK: begriffs-going-write-only https://begriffs.com/posts/2015-04-20-going-write-only.html
#+LINK: hackernews-notebookskills https://news.ycombinator.com/item?id=15052384
#+LINK: gnu-emacs https://www.gnu.org/software/emacs
#+LINK: org-mode https://orgmode.org
#+LINK: graham-makers-vs-managers http://paulgraham.com/makersschedule.html


#+BEGIN_PREVIEW
[[shia-labeouf-just-do-it]["Yesterday, you said tomorrow."]]  Entering the first week of being a full-time
graduate assistant, I want to start a more earnest attempt to share more of the
experience and the journey.  I've always maintained that the journey itself is
the worthier part, the ends only a different way to spell "beginning".
#+END_PREVIEW

Any time I internally commit to doing something, I remember the mildly
ridiculous quote from [[shia-labeouf-just-do-it][Shia LaBeouf's GreenScreen recording]] "Yesterday, you said
tomorrow".  Yesterday, I said tomorrow I would write this post.  Today is now
tomorrow and here goes.

I am starting my transition from a full-time software developer/site
reliability engineer to being a full-time graduate assistant, working towards a
PhD.  This post is a first in a series of posts where I will attempt to share
my research; technical tangents that come along the way; my thoughts and
inspirations; and likely many other random topics in between.  It's my
intention to write and share these fairly regularly.  Of course, we'll see how
the energy maintains through the weeks.

** Inspiration and Conflicts
   :PROPERTIES:
   :ID:       6a741000-6b5f-46e6-86bc-6c1e889a1d9c
   :END:

Let's traverse the path that planted the seed of this post, where it originally
came from and where it is now.  Finally, there's a bit of a dilemma to be posed
that I am not completely certain of the answer.

#+begin_quote
A lot can be said about each of the below.  In introducing them, my summaries
likely will not give justice to each.  There's a lot to unpack in each of these
and the connections may not be as obvious as I claim.  I certainly wish I had
the time or space to clearly delineate the various connections of points.
Instead, I encourage the deep dive into each; perhaps a different and
contradictory conclusion will be reached!
#+end_quote

*** Going Write Only
    :PROPERTIES:
    :ID:       d7a61189-bd44-43fc-84f0-3af13acdbdd2
    :END:

Back in 2015, [[begriffs-going-write-only][Joe Nelson posted "Going Write Only"]].  I was only just starting
to write blog posts, but I certainly didn't write with any particular
frequency.  "Going Write Only" was certainly inspiring, but I didn't have the
material nor the confidence to share and write that frequently, let alone make
a public commitment to that end.

The thesis of the going "write only" resonated, however, since I had similar
problems of consumption only, being in a state of "read only": go to work, read
HackerNews, check emails, wait, when did it become lunch time?  I clearly
couldn't articulate my frustration nor had the thought of breaking the cycle
and going write only fully awaken within me.

*** Makers vs Managers
    :PROPERTIES:
    :ID:       82fd574a-ac36-4de1-8961-441e676f08bf
    :END:

Around this time, 2016, I stumbled into [[graham-makers-vs-managers][Paul Graham's "Maker's Schedules vs
Manager's Schedules"]] post.  At the time of reading, I was poorly balancing both
schedules as a lead developer of a small team.  Issue triage and team
coordination consuming all remaining vestiges of my maker time, I immediately
connected with the principle of the article.

However, I failed in attempting any version of execution of the idea.  I never
had the clout or the gravitas to effectively move meetings to one side of the
day.  This has continued to be a struggle of mine as I have moved to different
roles in different companies.

*** Deep Work
    :PROPERTIES:
    :ID:       a2218724-9a1c-438f-9f19-ff8978ab9752
    :END:

Several years ago, approximately 2017, a friend and colleague of mine
recommended [[cal-newport-deep-work][Cal Newport's "Deep Work"]] to me.  I ate it up and again recommended
it to anyone who would listen.  The arguments against social media and other
distractions in life rang true with my own experience.  Being on top of emails
and other forms of communication already seemed wrong; how can we be deep in
thought _and_ be deeply connected to the various conversations that we might be
participating.  Newport's thesis and my own experience would both answer this
question with unequivocal "no".  Modality of tasks seems to be a more healthy
and appropriate model of working.  Work deeply without distraction, focus the
limited energy to the problem at hand.

*** (Laboratory) Notebook Skills
    :PROPERTIES:
    :ID:       37a50eaa-5f9c-43f6-9d4f-677eb22ac838
    :END:

The earliest reference I can find, [[notebookskills][Notebook Skills]] was posted to [[hackernews-notebookskills][HackerNews]]
in 2017.  Dutifully keeping a log of work, notes, results, thoughts would be
helpful in the likely event of context switches.  Being able to review these
notes to reintegrate into the flow would be invaluable.  How many times have I
been stuck on a problem feeling aimless in my approach, not sure where I left
off, unsure what changes were made, when, why they worked, or why they did not?

Switching to [[gnu-emacs][Emacs]] and starting to leverage [[org-mode][Org Mode]] as much as possible, these
skills seemed like a very natural extension.

However, I have certainly failed at maintaining this habit.  Our patterns and
behaviours are dramatically influenced by the amount of friction involved.

*** Show Your Work
    :PROPERTIES:
    :ID:       d62e9a24-dc8f-48e5-8c96-f267b5ddd0a8
    :END:

Recently, another colleague loaned me a copy of [[austin-kleon-steal-like-an-artist][Austin Kleon's "Steal Like an
Arist"]].  A very short book that describes and enumerates steps for investing in
your own craft.  The craft itself is not material to the discussion, the
content can be lifted to any creative endeavor without too much mental
gymnastics.

I was caught by the idea of sharing the work, even if it's not complete.

The next book in the series started by [[austin-kleon-steal-like-an-artist]["Steal Like an Artist"]] is [[austin-kleon-show-your-work]["Show Your
Work"]].  Naturally, I'm working my way through it (even convinced my colleague
whom recommended the first book to purchase the second book).  But for the past
week or so, I've been stuck thinking about "daily dispatches", posting a blog,
a tweet, an email, really anything that someone-- anyone-- may be interested
in.  Sharing the progress, snapshots of the creators mind or the project itself
if possible.  Again, the journey and experience is the worthier part.


** Confluence and Insolubility
    :PROPERTIES:
    :ID:       283f3968-78ff-4ed9-92d7-d9b25e11ebac
    :END:

Most of these articles dovetail or otherwise co-relate to each other in fairly
obvious and intuitive ways.  It's pretty easy to see parallels and connections
between [[begriffs-going-write-only]["Going Write Only"]], [[notebookskills][Notebook Skills]], and [[austin-kleon-show-your-work]["Show Your Work"]].  It's fairly
easy to draw connections between [[cal-newport-deep-work]["Deep Work"]] and [[graham-makers-vs-managers]["Makers Schedules vs Managers
Schedules"]].  Conversely, however, it's much less obvious to see the connection
between the former set of articles to the latter set.

Clearly, deep work is a necessary ingredient to creating.  It's less clear that
sharing the work in progress is a necessary component to making great work.
How to integrate these two ideas and philosophies has been the underlying root
of this post some weeks ago, the issue that begs for resolution.

The only answer that seems to hold water for me is this: by sharing the work in
progress, by forcing its digestion into something consumable to others helps
(re)organize the information; the information is more thoroughly understood and
accessible in our own brain as a result.  The final summit of acquiring
knowledge is to teach the knowledge gained.

** Challenges and Commitments
   :PROPERTIES:
   :ID:       0105c63f-e64d-4d7f-946a-19dcaf2591df
   :END:

As this new chapter opens, I want to make the commitment of going "write only";
the commitment to become a disciple of deep work; the commitment of keeping
good notes; and the commitment of sharing the process, the knowledge, the
tangents, and the thoughts along the journey.

Certainly, here be dragons.  There are many challenges to overcome.  How best
to manage and appropriate time for reading, developing, and writing (not to
mention other obligations that don't fit the scope here)?  How to maintain
balance and energy in the pursuit of the commitments and ultimate goals?  How
to overcome personal qualities that inhibit and scream out against everything
here?

These are not insurmountable hurdles, [[shia-labeouf-just-do-it]["Nothing is impossible"]].  Through
dedicated and concerted, these challenges can become merely small obstacles
which can be easily stepped over.
